version: '3'
services:
  elastic:
    image: manuelhatzl/elasticsearch_ingestattachment:7.3.0
    container_name: elastic
    restart: always
    environment:
      - node.name=elastic
      - discovery.seed_hosts=elastic2
      - cluster.initial_master_nodes=elastic,elastic2
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - http.max_content_length=1700MB
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - docfex-net
  elastic2:
    image: manuelhatzl/elasticsearch_ingestattachment:7.3.0
    container_name: elastic2
    restart: always
    environment:
      - node.name=elastic2
      - discovery.seed_hosts=elastic
      - cluster.initial_master_nodes=elastic,elastic2
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - http.max_content_length=1700MB
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - docfex-net
  docfex:
    image: manuelhatzl/docfex:latest
    container_name: docfex
    restart: always
    depends_on:
      - elastic
      - elastic2
    volumes:
      - /home/mhatzl/docfex/config:/opt/docfex/src/config
      - /home/mhatzl/Documents/BigDir:/mnt/basepath
    ports:
      - 5000:5000
    networks:
      - docfex-net

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  docfex-net:
